export interface SocioeducativoInterface {
    alta?: string,
    escuela?: number,
    alumno?: string,
    alumno_dni?: number,
    año?: number,
    circuito?: number,
    curso?: string,
    descripcion?: string,
    observacion?: string,
    region?: number,
    region_fecha?: string,
    fecha_jefatura?: string,
    ticket?: number,
    ticket_fecha?: string,
    userUid?: string,
    id?: string,
}
